# Data Science Principles and Practices Lab Week 2

Follow the instructions to complete each of these tasks. This set of exercises looks at Numpy and performing operations on numeric data. Do not worry if you do not complete them all in the timetabled lab session.

This is not assessed but will help you gain practical experience for the module exam and coursework.

For extra information about the functions provided by numpy, you can search the API documentation here:

https://numpy.org/doc/stable/

# Numpy

Numpy is a Python module for working with many dimensional arrays, performing efficient vectorised operations on them, and linear algebra. It also provides random number generation facilities.

 - tensorflow functions accept numpy arrays as inputs as well as tensor objects.
 - pandas can convert data frames or series into numpy arrays.
 - scikit accepts data passed as numpy arrays.

The main feature of numpy is that it provides efficient N-dimensional arrays and operations on them.

Numpy is typically imported as *np* to reduce typing.

```python
import numpy as np
```

Do this below.

In [1]:
import numpy as np

## Creating arrays

numpy arrays are objects of the numpy.array class, which is used to create arrays of any number of dimensions.

```python
a = np.array([[1,2,3],[4,5,6]])
```

Arrays can be created from tuples or lists. A single list will construct a one-dimensional array, and a list of lists will create a two dimensional array.

### Task 1.1

Create a two dimensional numpy array, with three rows and two columns, containing the numbers 1 to 6. The ordering of the numbers does not matter, but look at the output to see how the values are arranged.

*You can assign your array to a variable, e.g. a = np.array(....). To print out your array, you can then write a as the last line of your Jupyter code cell. Jupyter will print out the value in the last line of the code cell. For example:*

```python
a = np.array([1,2,3])
a
```

In [6]:
a = np.arange(1,7).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

Arrays can also be built using built-in constructors:

```python
b = np.ones((4,3)) # A 4 by 3 array of the value 1.0
c = np.zeros((3,4)) # A 3 by 4 array of the value 0.0
```

### Task 1.2

Try creating an array containing all ones, with 6 rows and 4 columns

## Working with Numpy arrays

The shape attribute gives the size of the array in each dimension, and the total number of dimensions.

```python
a = np.array([[1,2,3],[4,5,6]])
a.shape # (2,3)
a.ndim # 2
a.dtype # dtype('int64')
```

The dtype attribute tells us the data type of the values stored in the array. This can be specified when creating the array using an additional argument:

```python
a = np.array([[1,2,3],[4,5,6]],dtype=np.float64)
b = np.ones((4,3),dtype=np.int64)
```

### Task 1.3

Check the shape, number of dimensions (ndim) and data type of one of the arrays you created above.

## Indexing Numpy arrays

Numpy arrays are indexed in a similar way to Python arrays, with $0$ based indexing:

```python
a = np.array([1,2,3,4,5,6,7,8])
a[2:6] # slice from index 2 to 5
```

*Remember that the slice will go from the first index provided to the index before the last one (e.g. from index 2 to 5 when the range specified is 2:6).*

For multidimensional arrays, an index is provided in each dimension, or can be skipped with a single : to return all values in that dimension:

```python
a = np.arange(1,28).reshape((3,3,3))
a[1,:,2] # array([12, 15, 18])
```

### Task 1.4

An array b is provided below. Use indexing to return all values in the columns in the range 2 to 4 (inclusive). *You can use the columns at indices 2,3 and 4 - but remember that these will be the third, fourth and fifth columns in the array due to zero based indexing*. 

In [ ]:
b = np.arange(1,33).reshape((4,8))
b

In [ ]:
# put your answer here:


## Numpy ranges

As you can see in the previous task, to create ranges of values Numpy has an arange function that can be used to create an array filled with a range of values. It takes a starting value, end and step size.

```python
a = np.arange(2,10,2) # array([2, 4, 6, 8])
```

These can be reshaped to generate more complex N-dimensional arrays using the reshape method:

```python
a = np.arange(1,28).reshape(3,3,3)
```

# Broadcast operations

## Elementwise operators

The standard arithmetic operators like +,-,/ will act **elementwise** on arrays, and can be broadcast across a whole array.

For example, two arrays can be multiplied together *element by element*:

```python
a = np.arange(1,10).reshape(3,3)
b = np.arange(9,0,-1).reshape(3,3)
c = a*b
# c= array([[ 9, 16, 21],
#           [24, 25, 24],
#           [21, 16,  9]])
```

Notice that this is **not** matrix multiplication.



Operations like logarithms and exponentials can also be mapped across numpy arrays elementwise, simply by applying them to the array:

```python
a = np.arange(1,10).reshape(3,3)
np.power(a,3)
# array([[  1,   8,  27],
#        [ 64, 125, 216],
#        [343, 512, 729]])
```

This can be used with many functions including np.log, np.exp, np.power, np.sin}, and np.cos.

### Task 1.5

Try adding each of the values in arrays a and b provided below.

In [9]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
b = np.arange(9,0,-1).reshape(3,3)
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [10]:
c=a+b 
c

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

We can also broadcast logical and comparison operations over numpy arrays. For example we could use

```python
a = np.arange(1,10).reshape(3,3)
a<5
# array([[ True,  True,  True],
#        [ True, False, False],
#        [False, False, False]])
```


The numpy function to sum the values in an array will count True values as 1, and False as 0. So we can count the number of values in *a* less than 5 using:

```python
a = np.arange(1,10).reshape(3,3)
np.sum(a<5) # Returns 4
```

### Task 1.6

See if you can count the number of values greater than zero in the array c below: 

In [14]:
c = np.arange(96,-96,-3).reshape(8,8)
np.count_nonzero(c>0)

32

# Broadcasting in Pandas 

Just as in numpy, we can apply broadcasting operations in Pandas as well. This can be done simply by specifying the columns or rows to use, and the operation to perform (elementwise).

```python
bikes["properties.docksAvailable"]/bikes["properties.totalDocks"]
```

We can assign these values to a new column using:

```python
bikes["fractionOfDocks"] = bikes["properties.docksAvailable"]/bikes["properties.totalDocks"]
```

Try using Pandas with the code below from last week to calculate the fraction of electric bikes available out of the total number of bikes in each bike dock.

In [ ]:
import requests
import pandas as pd
indego_bikes_url = ("https://www.rideindego.com/stations/json/")
headers = {'User-Agent': "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:63.0) Gecko/20100101 Firefox/63.0"}
indego_bikes_data = requests.get(indego_bikes_url,headers=headers)
bikes = pd.io.json.json_normalize(indego_bikes_data.json()['features'])
bikes.head()

In [ ]:
bikes.columns

# Random numbers in Numpy

## Initialising the random number generator

We first need to initialise the random number generator, by creating an object that we can use to generate random numbers. *Note this is new in a recent update to Numpy*.

```python
rng = np.random.default_rng()
```

Do this below.

**If you are using an older version of Anaconda (as on the University Windows remote desktop, use:**

```python
rng = np.random
```

In [15]:
rng = np.random.default_rng()


## Generating random values

Numpy can generate random numbers from a variety of different distributions, but it can also make random selections or choices from a list of values.

```python
rng.choice(["Heads","Tails"])
```

Try this below to generate a single random dice roll for a six sided dice. Try running the cell multiple times and see how the output changes.

In [28]:
a= np.arange(1,7) 
a
rng.choice(a)


1

## Looping and if statements in Python

We can write simple Python loops to perform an operation multiple times using the *for* syntax. To specify the number of times to execute the code in the loop, we can provide a Python *range* object, specifying the number of loops we would like to make.

```python
for i in range(10): # Loop 10 times
    print(i)
```

Unlike in C or Java where { } are used, **in Python the code to loop over is specificed by indenting the code we would like to be contained within the for loop**.

The Python code *range(10)* will produce a range of values from 0 to 9.

We can also use *if* statements to perform operations when certain conditions are met:

```python
if a=="Heads":
    print(a) # Only run if variable a contains the value "Heads"
else:
    print("Not heads") # Only run if variable a does not contain the value "Heads"
```

**Just as with for loops, we specify the code we would like to execute if the condition is met using indentation.**

### Task 2.1

Write Python code using a *for* loop and *if* statement to generate random choices between the two values "Heads" and "Tails", and to count how many times each occurs. Start by doing this for 10 loop iterations, and look at the count of Heads occurring.

In [68]:
headcount= 0

for i in range(10000):
    a = rng.choice(["Heads", "Tails"])
    if a== "Heads":
     headcount += 1
    

print(headcount)


4945


Now run your code again but using 10000 iterations. You should notice that the final count of heads is closer to what we would expect in theory - roughly half of the 10000 simulated coin tosses.

### Task 2.2

Now write a Python for loop to roll a dice 4 times, and count the number of times the value 6 occurs.

In [69]:
sixes=0
for i in range(4):
    diceroll = rng.choice([1,2,3,4,5,6])
    if diceroll == 6:
        sixes+=1

print(sixes)
        

2


We can also generate a numpy array of random values rather than a single output using rng.choice:

```python
dice_rolls = rng.choice([1,2,3,4,5,6],size=4) # Generate 4 random choices from [1,2,3,4,5,6]
```

### Task 2.3

Try to use rng.choice to generate 1000000 coin tosses, and use numpy broadcasting to count the number of heads that occur. *Remember that you can use np.sum on an array of True or False values to count the number of times True occurs, and you can broadcast comparisons such as == over numpy arrays*

In [71]:
coin_tosses = rng.choice(["Heads","Tails"],size=1000000)
coin_tosses


array(['Heads', 'Heads', 'Tails', ..., 'Heads', 'Tails', 'Heads'],
      dtype='<U5')

Go back to your coin tossing code using a for loop above, and try running this for 1000000 coin tosses. Is using broadcasting in numpy faster or slower?

In [72]:
dice_rolls = rng.choice([1,2,3,4,5,6],size=(1000,4))
dice_rolls

array([[1, 3, 2, 2],
       [5, 3, 5, 4],
       [3, 1, 2, 4],
       ...,
       [6, 6, 5, 1],
       [4, 3, 1, 3],
       [4, 1, 2, 3]])

### Task 2.4*

*This task is extra challenging - attempt it if you have time.*

Try writing Python code to roll two dice 24 times, and count the number of times two sixes occurs. You can do this with a for loop first, but you can also try a numpy broadcast.

*In numpy you can use the broadcast operation & on two arrays of True/False values to return the logical AND operation on the two arrays elementwise*



### Task 2.5*

*This task is extra challenging - attempt it if you have time.*

You can use:

```python
dice_rolls = rng.choice([1,2,3,4,5,6],size=(1000,4))
```

to generate an array of 1000 rows of 4 dice rolls. Each element of the array is simply a random choice from the values 1 to 6, but this can be thought of as representing the results 1000 experiments where each time we roll a die 4 times.

With numpy it is possible to sum the values in an array along the rows (here corresponding to each experiment where we perform 4 dice rolls) to return an array of the sum of values on each row:

```python
np.sum(a,axis=1) # Sum an array along rows, returning an array of the sum of each row
```

Can you use this in combination with broadcasting == and > over numpy arrays to count the number of times *at least* one 6 occurs in 1000 experiments of rolling a dice 4 times?

*Remember that you can use np.sum on an array of True or False values to count the number of times True occurs.*